config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/weathers/search', to: 'weathers#search'
  post '/weathers/search', to: 'weathers#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/weather.rb
class Weather
  include ActiveModel::Model

  attr_accessor :cached, :address, :current_weather
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weathers_controller.rb
class WeathersController < ApplicationController

  WEATHER_EXPIRATION = 1800 # in seconds
  def search
    return if params[:address].blank?
    # params[:address]
    geo_location = fetch_coordinates(params[:address])
    unless geo_location
      # error page
      flash.now[:error] = 'Unable to find location'
      return
    end

    if geo_location['error']
      flash.now[:error] = 'API Error'
      return
    end

    first_result = geo_location['results'].first
    if first_result.dig('response', 'error')
      flash.now[:error] = 'Unable to find location'
      return
    end

    results = first_result.dig('response', 'results')
    location = results.first['location']
    zip_code = results.first['address_components']

    cached, weather = fetch_weather(zip_code, location)

    @weather = Weather.new(address: geo_location, current_weather: weather, cached: cached)
  end

  private

  # TODO: refactor all below to service

  def fetch_coordinates(address)
    geocode_key = ns_address(address)
    geocode = get_and_parse(geocode_key)
    unless geocode
      geocode_api = Geocodio::Gem.new(ENV['GEOCODIO_API_KEY'])
      geocode = geocode_api.geocode(params[:address])
      REDIS.set(geocode_key, geocode.to_json) unless geocode['error']
    end
    geocode
  end

  def ns_address(address)
    "ADDR:#{address}"
  end

  def fetch_weather(zip_code, location)
    weather_key = ns_weather(zip_code)
    weather = get_and_parse(weather_key)
    cached = !!weather
    unless weather
      api = OpenWeatherMap::API.new(ENV['OPENWEATHER_API_KEY'], 'en', 'imperial')
      weather_object = api.current([ location['lng'], location['lat'], ])
      weather = weather_object.as_json
      REDIS.set(weather_key, weather.to_json, ex: WEATHER_EXPIRATION)
    end
    [ cached, weather ]
  end

  def ns_weather(zip_code)
    "WEATHER:#{zip_code}"
  end

  def get_and_parse(key)
    rtn = REDIS.get(key)
    rtn ? JSON.parse(rtn) : rtn
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weathers/search.html.erb
<head>
  <style>
    table.weather { width: 100% }
    td.key { border:1px solid black; text-align:right }
    td.value { border:1px solid black }
    .cached { color: green; font-size: 18px }
    .uncached { color: lightgrey; font-size: 18px }
    .flash { margin: 5px; padding: 5px }
    .flash.error { background-color: red; color: white; }
    .flash.alert { background-color: yellow; }

  </style>
</head>
<h1>Weather</h1>

<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>

<div>
  <%= form_tag(weathers_search_path) do %>
    Address: <%= text_field_tag(:address) %> <%= submit_tag(value = "Submit") %>
  <% end %>
</div>

<% if @weather %>
  <% weather_conditions = @weather.current_weather['weather_conditions']%>
  <div style="padding: 20rem" 5rem>
    <table class="weather">
      <caption>
        <h3>Current Temperature</h3>
        <span title="<%= @weather.cached ? 'cached' : 'uncached' %>" class="<%= @weather.cached ? 'cached' : 'uncached' %>">&bull;</span>
        <%= @weather.address['results'].first.dig('response', 'input', 'formatted_address') %>
      </caption>
      <tr>
        <td class="key">Temperature</td>
        <td class="value"><%= sprintf('%dF', (weather_conditions['temperature'] || 0).round) %></td>
      </tr>
      <tr>
        <td class="key">High/Low</td>
        <td class="value"><%= sprintf('%dF / %dF', (weather_conditions['temp_max'] || 0).round, (weather_conditions['temp_min'] || 0).round) %></td>
      </tr>
    </table>
  </div>

  <blockquote>
    DEBUG:
    <pre><%= JSON.pretty_generate(@weather.as_json) %></pre>
  </blockquote>
<% end %>